version: '3.4'

services:

  server:
    build: 
      context: ./nginx
    networks:
      - three_containers_network
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build:
      context: ./node
    networks:
      - three_containers_network
    tty: true
    command: user node
    entrypoint: sh -c "npm install && npm run start"
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    

      #   healthcheck:
      # test: ["CMD", "curl" , "-f,", "http://localhost:3000 || exit 1"]
      # interval: 5s
      # timeout: 10s
      # retries: 20


  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=on
    restart: always
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - three_containers_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 20

networks:
  three_containers_network:
    driver: bridge

volumes:

  db:
    driver: local
  app:
    driver: local