version: '3.4'

services:

  server:
    build: 
      context: ./nginx
    networks:
      - three_containers_network
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build:
      context: ./node
    networks:
      - three_containers_network
    tty: true
    container_name: app
    ports:
      - "3000:3000"
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node index.js
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=on
    restart: always
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d

    networks:
      - three_containers_network  

networks:
  three_containers_network:
    driver: bridge  
volumes:
  db:
    driver: local